/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores.node;

import compiladores.analysis.*;

@SuppressWarnings("nls")
public final class AAvalieComandos extends PComandos
{
    private PExpOuElogica _expOuElogica_;

    public AAvalieComandos()
    {
        // Constructor
    }

    public AAvalieComandos(
        @SuppressWarnings("hiding") PExpOuElogica _expOuElogica_)
    {
        // Constructor
        setExpOuElogica(_expOuElogica_);

    }

    @Override
    public Object clone()
    {
        return new AAvalieComandos(
            cloneNode(this._expOuElogica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAvalieComandos(this);
    }

    public PExpOuElogica getExpOuElogica()
    {
        return this._expOuElogica_;
    }

    public void setExpOuElogica(PExpOuElogica node)
    {
        if(this._expOuElogica_ != null)
        {
            this._expOuElogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expOuElogica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expOuElogica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expOuElogica_ == child)
        {
            this._expOuElogica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expOuElogica_ == oldChild)
        {
            setExpOuElogica((PExpOuElogica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
