/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores.node;

import compiladores.analysis.*;

@SuppressWarnings("nls")
public final class AComandoAvalieComandos extends PComandos
{
    private TAvalie _avalie_;
    private TAParentese _aParentese_;
    private PExpOuElogica _expOuElogica_;
    private TFParentese _fParentese_;
    private PCasoComando _casoComando_;
    private PSenaoComandoDoispontos _senaoComandoDoispontos_;
    private TFimAvalie _fimAvalie_;
    private TPontoEVirg _pontoEVirg_;

    public AComandoAvalieComandos()
    {
        // Constructor
    }

    public AComandoAvalieComandos(
        @SuppressWarnings("hiding") TAvalie _avalie_,
        @SuppressWarnings("hiding") TAParentese _aParentese_,
        @SuppressWarnings("hiding") PExpOuElogica _expOuElogica_,
        @SuppressWarnings("hiding") TFParentese _fParentese_,
        @SuppressWarnings("hiding") PCasoComando _casoComando_,
        @SuppressWarnings("hiding") PSenaoComandoDoispontos _senaoComandoDoispontos_,
        @SuppressWarnings("hiding") TFimAvalie _fimAvalie_,
        @SuppressWarnings("hiding") TPontoEVirg _pontoEVirg_)
    {
        // Constructor
        setAvalie(_avalie_);

        setAParentese(_aParentese_);

        setExpOuElogica(_expOuElogica_);

        setFParentese(_fParentese_);

        setCasoComando(_casoComando_);

        setSenaoComandoDoispontos(_senaoComandoDoispontos_);

        setFimAvalie(_fimAvalie_);

        setPontoEVirg(_pontoEVirg_);

    }

    @Override
    public Object clone()
    {
        return new AComandoAvalieComandos(
            cloneNode(this._avalie_),
            cloneNode(this._aParentese_),
            cloneNode(this._expOuElogica_),
            cloneNode(this._fParentese_),
            cloneNode(this._casoComando_),
            cloneNode(this._senaoComandoDoispontos_),
            cloneNode(this._fimAvalie_),
            cloneNode(this._pontoEVirg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoAvalieComandos(this);
    }

    public TAvalie getAvalie()
    {
        return this._avalie_;
    }

    public void setAvalie(TAvalie node)
    {
        if(this._avalie_ != null)
        {
            this._avalie_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._avalie_ = node;
    }

    public TAParentese getAParentese()
    {
        return this._aParentese_;
    }

    public void setAParentese(TAParentese node)
    {
        if(this._aParentese_ != null)
        {
            this._aParentese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aParentese_ = node;
    }

    public PExpOuElogica getExpOuElogica()
    {
        return this._expOuElogica_;
    }

    public void setExpOuElogica(PExpOuElogica node)
    {
        if(this._expOuElogica_ != null)
        {
            this._expOuElogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expOuElogica_ = node;
    }

    public TFParentese getFParentese()
    {
        return this._fParentese_;
    }

    public void setFParentese(TFParentese node)
    {
        if(this._fParentese_ != null)
        {
            this._fParentese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fParentese_ = node;
    }

    public PCasoComando getCasoComando()
    {
        return this._casoComando_;
    }

    public void setCasoComando(PCasoComando node)
    {
        if(this._casoComando_ != null)
        {
            this._casoComando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._casoComando_ = node;
    }

    public PSenaoComandoDoispontos getSenaoComandoDoispontos()
    {
        return this._senaoComandoDoispontos_;
    }

    public void setSenaoComandoDoispontos(PSenaoComandoDoispontos node)
    {
        if(this._senaoComandoDoispontos_ != null)
        {
            this._senaoComandoDoispontos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senaoComandoDoispontos_ = node;
    }

    public TFimAvalie getFimAvalie()
    {
        return this._fimAvalie_;
    }

    public void setFimAvalie(TFimAvalie node)
    {
        if(this._fimAvalie_ != null)
        {
            this._fimAvalie_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fimAvalie_ = node;
    }

    public TPontoEVirg getPontoEVirg()
    {
        return this._pontoEVirg_;
    }

    public void setPontoEVirg(TPontoEVirg node)
    {
        if(this._pontoEVirg_ != null)
        {
            this._pontoEVirg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoEVirg_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._avalie_)
            + toString(this._aParentese_)
            + toString(this._expOuElogica_)
            + toString(this._fParentese_)
            + toString(this._casoComando_)
            + toString(this._senaoComandoDoispontos_)
            + toString(this._fimAvalie_)
            + toString(this._pontoEVirg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._avalie_ == child)
        {
            this._avalie_ = null;
            return;
        }

        if(this._aParentese_ == child)
        {
            this._aParentese_ = null;
            return;
        }

        if(this._expOuElogica_ == child)
        {
            this._expOuElogica_ = null;
            return;
        }

        if(this._fParentese_ == child)
        {
            this._fParentese_ = null;
            return;
        }

        if(this._casoComando_ == child)
        {
            this._casoComando_ = null;
            return;
        }

        if(this._senaoComandoDoispontos_ == child)
        {
            this._senaoComandoDoispontos_ = null;
            return;
        }

        if(this._fimAvalie_ == child)
        {
            this._fimAvalie_ = null;
            return;
        }

        if(this._pontoEVirg_ == child)
        {
            this._pontoEVirg_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._avalie_ == oldChild)
        {
            setAvalie((TAvalie) newChild);
            return;
        }

        if(this._aParentese_ == oldChild)
        {
            setAParentese((TAParentese) newChild);
            return;
        }

        if(this._expOuElogica_ == oldChild)
        {
            setExpOuElogica((PExpOuElogica) newChild);
            return;
        }

        if(this._fParentese_ == oldChild)
        {
            setFParentese((TFParentese) newChild);
            return;
        }

        if(this._casoComando_ == oldChild)
        {
            setCasoComando((PCasoComando) newChild);
            return;
        }

        if(this._senaoComandoDoispontos_ == oldChild)
        {
            setSenaoComandoDoispontos((PSenaoComandoDoispontos) newChild);
            return;
        }

        if(this._fimAvalie_ == oldChild)
        {
            setFimAvalie((TFimAvalie) newChild);
            return;
        }

        if(this._pontoEVirg_ == oldChild)
        {
            setPontoEVirg((TPontoEVirg) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
