/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores.node;

import java.util.*;
import compiladores.analysis.*;

@SuppressWarnings("nls")
public final class AComandoVirgulaComandoListVirg extends PComandoListVirg
{
    private final LinkedList<PComandoPontoVirg> _comandoPontoVirg_ = new LinkedList<PComandoPontoVirg>();

    public AComandoVirgulaComandoListVirg()
    {
        // Constructor
    }

    public AComandoVirgulaComandoListVirg(
        @SuppressWarnings("hiding") List<?> _comandoPontoVirg_)
    {
        // Constructor
        setComandoPontoVirg(_comandoPontoVirg_);

    }

    @Override
    public Object clone()
    {
        return new AComandoVirgulaComandoListVirg(
            cloneList(this._comandoPontoVirg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoVirgulaComandoListVirg(this);
    }

    public LinkedList<PComandoPontoVirg> getComandoPontoVirg()
    {
        return this._comandoPontoVirg_;
    }

    public void setComandoPontoVirg(List<?> list)
    {
        for(PComandoPontoVirg e : this._comandoPontoVirg_)
        {
            e.parent(null);
        }
        this._comandoPontoVirg_.clear();

        for(Object obj_e : list)
        {
            PComandoPontoVirg e = (PComandoPontoVirg) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._comandoPontoVirg_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoPontoVirg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoPontoVirg_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PComandoPontoVirg> i = this._comandoPontoVirg_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComandoPontoVirg) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
