/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores.node;

import compiladores.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracaoListaDeclaracao extends PDeclaracao
{
    private PDeclaracaoList _declaracaoList_;

    public ADeclaracaoListaDeclaracao()
    {
        // Constructor
    }

    public ADeclaracaoListaDeclaracao(
        @SuppressWarnings("hiding") PDeclaracaoList _declaracaoList_)
    {
        // Constructor
        setDeclaracaoList(_declaracaoList_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracaoListaDeclaracao(
            cloneNode(this._declaracaoList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracaoListaDeclaracao(this);
    }

    public PDeclaracaoList getDeclaracaoList()
    {
        return this._declaracaoList_;
    }

    public void setDeclaracaoList(PDeclaracaoList node)
    {
        if(this._declaracaoList_ != null)
        {
            this._declaracaoList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracaoList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declaracaoList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declaracaoList_ == child)
        {
            this._declaracaoList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declaracaoList_ == oldChild)
        {
            setDeclaracaoList((PDeclaracaoList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
