/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores.node;

import java.util.*;
import compiladores.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracaoListDeclaracaoList extends PDeclaracaoList
{
    private final LinkedList<PDeclaracoes> _declaracoes_ = new LinkedList<PDeclaracoes>();

    public ADeclaracaoListDeclaracaoList()
    {
        // Constructor
    }

    public ADeclaracaoListDeclaracaoList(
        @SuppressWarnings("hiding") List<?> _declaracoes_)
    {
        // Constructor
        setDeclaracoes(_declaracoes_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracaoListDeclaracaoList(
            cloneList(this._declaracoes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracaoListDeclaracaoList(this);
    }

    public LinkedList<PDeclaracoes> getDeclaracoes()
    {
        return this._declaracoes_;
    }

    public void setDeclaracoes(List<?> list)
    {
        for(PDeclaracoes e : this._declaracoes_)
        {
            e.parent(null);
        }
        this._declaracoes_.clear();

        for(Object obj_e : list)
        {
            PDeclaracoes e = (PDeclaracoes) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._declaracoes_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declaracoes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declaracoes_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PDeclaracoes> i = this._declaracoes_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDeclaracoes) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
