/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores.node;

import compiladores.analysis.*;

@SuppressWarnings("nls")
public final class AElogicaVirgExpVirg extends PExpVirg
{
    private PExpLogica _expLogica_;
    private TVirg _virg_;

    public AElogicaVirgExpVirg()
    {
        // Constructor
    }

    public AElogicaVirgExpVirg(
        @SuppressWarnings("hiding") PExpLogica _expLogica_,
        @SuppressWarnings("hiding") TVirg _virg_)
    {
        // Constructor
        setExpLogica(_expLogica_);

        setVirg(_virg_);

    }

    @Override
    public Object clone()
    {
        return new AElogicaVirgExpVirg(
            cloneNode(this._expLogica_),
            cloneNode(this._virg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElogicaVirgExpVirg(this);
    }

    public PExpLogica getExpLogica()
    {
        return this._expLogica_;
    }

    public void setExpLogica(PExpLogica node)
    {
        if(this._expLogica_ != null)
        {
            this._expLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica_ = node;
    }

    public TVirg getVirg()
    {
        return this._virg_;
    }

    public void setVirg(TVirg node)
    {
        if(this._virg_ != null)
        {
            this._virg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virg_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogica_)
            + toString(this._virg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogica_ == child)
        {
            this._expLogica_ = null;
            return;
        }

        if(this._virg_ == child)
        {
            this._virg_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogica_ == oldChild)
        {
            setExpLogica((PExpLogica) newChild);
            return;
        }

        if(this._virg_ == oldChild)
        {
            setVirg((TVirg) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
