/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores.node;

import compiladores.analysis.*;

@SuppressWarnings("nls")
public final class AElogicaFatorMaiorigualExpLogicaFator extends PExpLogicaFator
{
    private PExp _exp_;
    private TMaiorOuIgualQ _maiorOuIgualQ_;
    private PTermo _termo_;

    public AElogicaFatorMaiorigualExpLogicaFator()
    {
        // Constructor
    }

    public AElogicaFatorMaiorigualExpLogicaFator(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TMaiorOuIgualQ _maiorOuIgualQ_,
        @SuppressWarnings("hiding") PTermo _termo_)
    {
        // Constructor
        setExp(_exp_);

        setMaiorOuIgualQ(_maiorOuIgualQ_);

        setTermo(_termo_);

    }

    @Override
    public Object clone()
    {
        return new AElogicaFatorMaiorigualExpLogicaFator(
            cloneNode(this._exp_),
            cloneNode(this._maiorOuIgualQ_),
            cloneNode(this._termo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElogicaFatorMaiorigualExpLogicaFator(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TMaiorOuIgualQ getMaiorOuIgualQ()
    {
        return this._maiorOuIgualQ_;
    }

    public void setMaiorOuIgualQ(TMaiorOuIgualQ node)
    {
        if(this._maiorOuIgualQ_ != null)
        {
            this._maiorOuIgualQ_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maiorOuIgualQ_ = node;
    }

    public PTermo getTermo()
    {
        return this._termo_;
    }

    public void setTermo(PTermo node)
    {
        if(this._termo_ != null)
        {
            this._termo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._maiorOuIgualQ_)
            + toString(this._termo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._maiorOuIgualQ_ == child)
        {
            this._maiorOuIgualQ_ = null;
            return;
        }

        if(this._termo_ == child)
        {
            this._termo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._maiorOuIgualQ_ == oldChild)
        {
            setMaiorOuIgualQ((TMaiorOuIgualQ) newChild);
            return;
        }

        if(this._termo_ == oldChild)
        {
            setTermo((PTermo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
