/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores.node;

import compiladores.analysis.*;

@SuppressWarnings("nls")
public final class AExpLogicaXorExpLogica extends PExpLogica
{
    private PExpLogica _expLogica_;
    private TXor _xor_;
    private PExpLogicaTermo _expLogicaTermo_;

    public AExpLogicaXorExpLogica()
    {
        // Constructor
    }

    public AExpLogicaXorExpLogica(
        @SuppressWarnings("hiding") PExpLogica _expLogica_,
        @SuppressWarnings("hiding") TXor _xor_,
        @SuppressWarnings("hiding") PExpLogicaTermo _expLogicaTermo_)
    {
        // Constructor
        setExpLogica(_expLogica_);

        setXor(_xor_);

        setExpLogicaTermo(_expLogicaTermo_);

    }

    @Override
    public Object clone()
    {
        return new AExpLogicaXorExpLogica(
            cloneNode(this._expLogica_),
            cloneNode(this._xor_),
            cloneNode(this._expLogicaTermo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpLogicaXorExpLogica(this);
    }

    public PExpLogica getExpLogica()
    {
        return this._expLogica_;
    }

    public void setExpLogica(PExpLogica node)
    {
        if(this._expLogica_ != null)
        {
            this._expLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica_ = node;
    }

    public TXor getXor()
    {
        return this._xor_;
    }

    public void setXor(TXor node)
    {
        if(this._xor_ != null)
        {
            this._xor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._xor_ = node;
    }

    public PExpLogicaTermo getExpLogicaTermo()
    {
        return this._expLogicaTermo_;
    }

    public void setExpLogicaTermo(PExpLogicaTermo node)
    {
        if(this._expLogicaTermo_ != null)
        {
            this._expLogicaTermo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogicaTermo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogica_)
            + toString(this._xor_)
            + toString(this._expLogicaTermo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogica_ == child)
        {
            this._expLogica_ = null;
            return;
        }

        if(this._xor_ == child)
        {
            this._xor_ = null;
            return;
        }

        if(this._expLogicaTermo_ == child)
        {
            this._expLogicaTermo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogica_ == oldChild)
        {
            setExpLogica((PExpLogica) newChild);
            return;
        }

        if(this._xor_ == oldChild)
        {
            setXor((TXor) newChild);
            return;
        }

        if(this._expLogicaTermo_ == oldChild)
        {
            setExpLogicaTermo((PExpLogicaTermo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
