/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores.node;

import java.util.*;
import compiladores.analysis.*;

@SuppressWarnings("nls")
public final class AExpListExpList extends PExpList
{
    private final LinkedList<PExpVirg> _expVirg_ = new LinkedList<PExpVirg>();

    public AExpListExpList()
    {
        // Constructor
    }

    public AExpListExpList(
        @SuppressWarnings("hiding") List<?> _expVirg_)
    {
        // Constructor
        setExpVirg(_expVirg_);

    }

    @Override
    public Object clone()
    {
        return new AExpListExpList(
            cloneList(this._expVirg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpListExpList(this);
    }

    public LinkedList<PExpVirg> getExpVirg()
    {
        return this._expVirg_;
    }

    public void setExpVirg(List<?> list)
    {
        for(PExpVirg e : this._expVirg_)
        {
            e.parent(null);
        }
        this._expVirg_.clear();

        for(Object obj_e : list)
        {
            PExpVirg e = (PExpVirg) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._expVirg_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expVirg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expVirg_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PExpVirg> i = this._expVirg_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpVirg) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
