/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores.node;

import compiladores.analysis.*;

@SuppressWarnings("nls")
public final class AExpVirgExpVirg extends PExpVirg
{
    private PExp _exp_;
    private TVirg _virg_;

    public AExpVirgExpVirg()
    {
        // Constructor
    }

    public AExpVirgExpVirg(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TVirg _virg_)
    {
        // Constructor
        setExp(_exp_);

        setVirg(_virg_);

    }

    @Override
    public Object clone()
    {
        return new AExpVirgExpVirg(
            cloneNode(this._exp_),
            cloneNode(this._virg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpVirgExpVirg(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TVirg getVirg()
    {
        return this._virg_;
    }

    public void setVirg(TVirg node)
    {
        if(this._virg_ != null)
        {
            this._virg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virg_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._virg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._virg_ == child)
        {
            this._virg_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._virg_ == oldChild)
        {
            setVirg((TVirg) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
