/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores.node;

import compiladores.analysis.*;

@SuppressWarnings("nls")
public final class APassoComandos extends PComandos
{
    private PVar _var_;
    private TNum _a_;
    private TNum _b_;
    private TNum _c_;

    public APassoComandos()
    {
        // Constructor
    }

    public APassoComandos(
        @SuppressWarnings("hiding") PVar _var_,
        @SuppressWarnings("hiding") TNum _a_,
        @SuppressWarnings("hiding") TNum _b_,
        @SuppressWarnings("hiding") TNum _c_)
    {
        // Constructor
        setVar(_var_);

        setA(_a_);

        setB(_b_);

        setC(_c_);

    }

    @Override
    public Object clone()
    {
        return new APassoComandos(
            cloneNode(this._var_),
            cloneNode(this._a_),
            cloneNode(this._b_),
            cloneNode(this._c_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPassoComandos(this);
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public TNum getA()
    {
        return this._a_;
    }

    public void setA(TNum node)
    {
        if(this._a_ != null)
        {
            this._a_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._a_ = node;
    }

    public TNum getB()
    {
        return this._b_;
    }

    public void setB(TNum node)
    {
        if(this._b_ != null)
        {
            this._b_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._b_ = node;
    }

    public TNum getC()
    {
        return this._c_;
    }

    public void setC(TNum node)
    {
        if(this._c_ != null)
        {
            this._c_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._c_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._a_)
            + toString(this._b_)
            + toString(this._c_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._a_ == child)
        {
            this._a_ = null;
            return;
        }

        if(this._b_ == child)
        {
            this._b_ = null;
            return;
        }

        if(this._c_ == child)
        {
            this._c_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        if(this._a_ == oldChild)
        {
            setA((TNum) newChild);
            return;
        }

        if(this._b_ == oldChild)
        {
            setB((TNum) newChild);
            return;
        }

        if(this._c_ == oldChild)
        {
            setC((TNum) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
