/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores.analysis;

import compiladores.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTPrograma(TPrograma node);
    void caseTInicio(TInicio node);
    void caseTFimPrograma(TFimPrograma node);
    void caseTSe(TSe node);
    void caseTSenao(TSenao node);
    void caseTEnquanto(TEnquanto node);
    void caseTPara(TPara node);
    void caseTAvalie(TAvalie node);
    void caseTCaso(TCaso node);
    void caseTVerdadeiro(TVerdadeiro node);
    void caseTFalso(TFalso node);
    void caseTLeia(TLeia node);
    void caseTEscreva(TEscreva node);
    void caseTInteiro(TInteiro node);
    void caseTReal(TReal node);
    void caseTBooleano(TBooleano node);
    void caseTString(TString node);
    void caseTNao(TNao node);
    void caseTE(TE node);
    void caseTOu(TOu node);
    void caseTId(TId node);
    void caseTNum(TNum node);
    void caseTNumreal(TNumreal node);
    void caseTCaractere(TCaractere node);
    void caseTBlank(TBlank node);
    void caseTComentarioBloco(TComentarioBloco node);
    void caseTComentarioCorpo(TComentarioCorpo node);
    void caseTComentarioFimBloco(TComentarioFimBloco node);
    void caseTEstrela(TEstrela node);
    void caseTBarra(TBarra node);
    void caseTComentarioLinha(TComentarioLinha node);
    void caseTDoisPontos(TDoisPontos node);
    void caseTPontoEVirg(TPontoEVirg node);
    void caseTVirg(TVirg node);
    void caseTAParentese(TAParentese node);
    void caseTFParentese(TFParentese node);
    void caseTAColchete(TAColchete node);
    void caseTFColchete(TFColchete node);
    void caseTAspasSimples(TAspasSimples node);
    void caseTAspasDuplas(TAspasDuplas node);
    void caseTSublinhado(TSublinhado node);
    void caseTMais(TMais node);
    void caseTMenos(TMenos node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTMod(TMod node);
    void caseTMaiorq(TMaiorq node);
    void caseTMenorq(TMenorq node);
    void caseTMenorOuIgualQ(TMenorOuIgualQ node);
    void caseTMaiorOuIgualQ(TMaiorOuIgualQ node);
    void caseTIgual(TIgual node);
    void caseTDiferente(TDiferente node);
    void caseTAtrib(TAtrib node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
